import type { ConciergeConfig } from "@/lib/denis/config/concierge-config.schema";

/** Platform defaults — merged under org → location overrides. */
export const CONCIERGE_PLATFORM_DEFAULTS: ConciergeConfig = {
  version: 1,
  enabled: true,
  persona: {
    name: "Denis",
    role: "Head waiter",
    tone: "warm_short",
    greetingStyle: "offer_drink_or_food",
    forbiddenPhrases: [
      "samo digitalni konobar",
      "digital waiter",
      "ne mogu da pozovem",
      "cannot call",
      "as an ai",
      "language model",
    ],
    emoji: false,
    maxWordsPerReply: 45,
  },
  language: {
    venueDefault: "de",
    followGuest: true,
    fallbackWhenUnknown: "venue",
  },
  context: {
    scroll: true,
    tableOrders: true,
    orderStatus: true,
    manualCart: true,
    orderHistory: true,
    includePairingHistory: true,
    maxContextTokens: 2000,
    adaptiveContext: true,
    minContextTokens: 500,
  },
  ordering: {
    flow: "denis_short",
    requireExplicitConfirm: true,
    allowMultiItemParse: true,
    slotExtractEnabled: false,
    actLayerEnabled: false,
    actDryRun: true,
    actSubmitEnabled: false,
    defaultServeSize: null,
    maxItemsPerOrder: 50,
    maxQuantityPerLine: 20,
  },
  upsell: {
    foodAfterDrinks: true,
    foodAfterDrinksProductIds: null,
    dessertAfterDelivered: true,
    dessertDelayMinutes: 20,
    maxUpsellsPerSession: 2,
    respectDecline: true,
  },
  proactive: {
    enabled: true,
    browseNudgeMinutes: 3,
    pairing: true,
    dessert: true,
    slowKitchen: true,
    slowKitchenThresholdMinutes: 25,
    reviewPrompt: true,
    reviewPromptAfterDelivered: true,
    minMinutesBetweenProactive: 4,
    shareSessionWithChat: true,
    guestWelcome: true,
    guestWelcomeSeconds: 30,
    browseFollowUp: true,
    browseFollowUpSeconds: 60,
    billPrompt: true,
    billPromptMinutes: 20,
    orderDelay: true,
    orderDelayMinutes: 15,
    popularityPairing: true,
    popularityBrowseMinutes: 1,
    offerEnrich: false,
    staffTableIdle: true,
    staffTableIdleMinutes: 15,
    staffAllergy: true,
    staffWaiterRequest: true,
    dailyPrep: true,
    dailyPrepHour: "08:00",
    dailyReport: true,
    dailyReportHour: "23:00",
  },
  policy: {
    allergiesStrict: true,
    blockAlcoholWithoutFood: false,
    blockOrderingWhenClosed: true,
    maxOrderTotal: null,
    requireServeSizeForDrinks: true,
  },
  llm: {
    model: null,
    fallbackModel: null,
    temperatureOrdering: 0.2,
    temperatureRecommend: 0.5,
    parseRetryAttempts: 1,
    skipLlmWhenPossible: true,
    narrateWithLlm: false,
    slotExtractWithLlm: false,
  },
  handoff: {
    waiterCall: true,
    paymentHint: true,
    liveExecution: true,
    phrases: [],
  },
  experiments: {
    playbookVariant: null,
    exampleSetId: null,
  },
  credits: {
    chargeProactive: false,
    chargeDeterministic: false,
  },
  rollout: {
    mode: "shadow",
    canaryPercent: 10,
    tableSessionActorEnabled: false,
  },
  party: {
    mode: "shared_cart",
  },
  ops: {
    staffHintsEnabled: true,
    rushSkipUpsell: true,
    kdsStressSkipUpsell: true,
    floorGraphEnabled: false,
    unifiedOperationalContextEnabled: false,
    unifiedOperationalContextCanaryPercent: 0,
    agenticToolLoop: {
      enabled: false,
      shadowOnly: true,
      canaryPercent: 0,
      maxRounds: 3,
      legacySingleCallFallback: true,
    },
    autoRushEnabled: false,
    autoRushBacklogMinutes: 20,
    stationQuestions: {
      enabled: true,
      foodSlaMinutes: 12,
      drinkSlaMinutes: 4,
      pendingAcceptMinutes: 2,
      readyPickupMinutes: 2,
      cooldownMinutes: 4,
      maxOpenPerStation: 3,
      expirySeconds: 90,
      meteredByCredits: false,
    },
    stationAwareTell: false,
    tableTempo: {
      enabled: false,
      browsingStalledMinutes: 10,
      drinkBeerMinutes: 20,
      drinkWineMinutes: 25,
      drinkCoffeeMinutes: 10,
      drinkDefaultMinutes: 20,
      drinksFinishedGraceMinutes: 2,
      postMealIdleMinutes: 15,
      cooldownMinutes: 20,
      guestIgnoredMinutes: 8,
    },
    dessertWindow: {
      enabled: false,
      graceMinutes: 2,
      mainCourseConsumptionMinutes: 18,
      windowMaxMinutes: 12,
      includeCoffee: true,
      includeDigestif: false,
      cooldownMinutes: 25,
      minAcceptRate: 0.12,
      minImpressionsForLearning: 8,
    },
    serviceRecovery: {
      enabled: false,
      gestures: ["dessert_on_house", "drink_on_house"],
      waitSilenceMinutes: 18,
      reviewBlockMinutes: 120,
    },
    tableTurnaround: {
      enabled: false,
      busSlaMinutes: 8,
    },
    lossPrevention: {
      enabled: false,
      voidLadderEnabled: false,
      transferInvariantsEnabled: false,
      paymentGuardrailsEnabled: false,
      cashRiskEnabled: false,
      discountPatternsEnabled: false,
      suspiciousReportEnabled: false,
      discountDeviationMultiplier: 2,
      digestMaxItems: 10,
      cashSessionOpenMinutes: 120,
    },
  },
  learning: {
    learnedEdgesEnabled: false,
    minAcceptRateForSuggestion: 0.15,
    minImpressionsForSuggestion: 3,
    crossVenue: {
      enabled: true,
      venueType: "casual",
    },
  },
  thresholdOptimizer: {
    autoApply: false,
  },
  memory: {
    returnGuestEnabled: false,
    memoryTtlDays: 90,
    consentPromptTemplate: null,
  },
  surfaces: {
    // Guest voice INPUT (mic/STT) off by default — not tested/verified
    // enough yet (real bugs found in the wake-word/push-to-talk layer this
    // session). Priority is kitchen/bar (voiceStaffEnabled) first.
    voiceEnabled: false,
    voiceTtsEnabled: true,
    voiceStaffEnabled: true,
  },
  mentalModel: {
    enabled: false,
    mode: "off",
    nudgeBudgetDefault: 3,
    nudgeBudgetEnthusiastic: 6,
    declineCooldownSeconds: 180,
    frustrationEscalateThreshold: "mild",
    confidenceFallbackThreshold: 0.4,
  },
  intervention: {
    enabled: false,
    mode: "off",
  },
  rhythm: {
    enabled: false,
    mode: "off",
    minSampleSessions: 8,
    minConfidence: 0.4,
    ops: {
      rushAlerts: false,
      staffingHints: false,
      rushThreshold: 1.8,
      targetSessionsPerWaiter: 4,
      staffingOccupancyThreshold: 0.55,
    },
  },
  intelligence: {
    contextAwareness: true,
    timezone: "Europe/Belgrade",
    dailyMenuLabel: null,
    localSportsTeam: null,
    weather: {
      enabled: true,
      openWeatherMapApiKey: null,
      latitude: null,
      longitude: null,
    },
  },
  pipeline: {
    enabled: true,
    preSkills: ["pre.allergy_guard", "pre.cart_state", "pre.menu_filter"],
    postSkills: [
      "post.order_validator",
      "post.price_check",
      "post.tone_guard",
      "post.safety_guard",
    ],
  },
};

/** Deep clone for tests/runtime paths that must not mutate platform defaults. */
export function cloneConciergePlatformDefaults(): ConciergeConfig {
  return structuredClone(CONCIERGE_PLATFORM_DEFAULTS);
}

export const CONCIERGE_CONFIG_CACHE_TTL_SECONDS = 300;
export const CONCIERGE_CONFIG_CACHE_KEY_PREFIX = "ai:config:";

export function conciergeConfigCacheKey(locationId: string): string {
  return `${CONCIERGE_CONFIG_CACHE_KEY_PREFIX}${locationId}`;
}
